[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "analyzer"
version = "0.0.1"
requires-python = ">=3.7"
dependencies = [
    "nicegui",
    "drain3",
    "marshmallow"
]