/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.analyzer

import org.analyzer.parsers.DictParser

fun main() {
    val parser = DictParser()

    while (true) {
      val input = readLine()
      if (input != null) {
          val pattern = parser.extractPatternFromLine(input)
          val id = parser.putPattern(pattern)
          pattern.humanReadable().let {
              println("id = $id for $it ($input)")
          }
      }
    }
}
